const id=new URLSearchParams(location.search).get("id");const app=document.getElementById("app");
const names={porcentaje:"Calculadora de porcentaje",iva:"Calculadora de IVA",edad:"Calculadora de edad",descuento:"Calculadora de descuento",regla:"Regla de tres",media:"Calculadora de media",tiempo:"Calculadora de tiempo",conversor:"Conversor de unidades",numero:"Números aleatorios",nombres:"Generador de nombres",password:"Generador de contraseñas",ruleta:"Ruleta aleatoria",equipos:"Generador de equipos",decision:"¿Qué elijo?",notas:"Calculadora de notas",ponderada:"Media ponderada",pomodoro:"Temporizador Pomodoro",palabras:"Contador de palabras",caracteres:"Contador de caracteres",sueldo:"Calculadora de sueldo",beneficio:"Calculadora de beneficio",margen:"Calculadora de margen",interes:"Interés compuesto",imc:"Calculadora de IMC",calorias:"Calculadora de calorías",ritmo:"Calculadora de ritmo",distancia:"Distancia / tiempo","gaming-generador":"Generadores gaming","gaming-ruleta":"Ruletas gaming","gaming-test":"Tests gaming",stranger:"Test Stranger Things",marvel:"Test Marvel",dc:"Test DC",pokemon:"Test Pokémon","mas-tests":"Más tests"};
function page(title,body){document.title=title+" | SuperWeb";app.innerHTML=`<a class="back" href="index.html">← Todas las herramientas</a><h1>${title}</h1><div class="box">${body}</div>`}
function f(label,id,type="number"){return `<div class="field"><label>${label}</label><input id="${id}" type="${type}"></div>`}
function test(title,questions,results){let q=questions.map((x,i)=>`<div class="field"><label>${i+1}. ${x[0]}</label><select id="q${i}">${x.slice(1).map((v,j)=>`<option value="${j}">${v}</option>`).join("")}</select></div>`).join("");page(title,q+`<button class="btn" onclick="let s=[...document.querySelectorAll('select')].reduce((a,e)=>a+(+e.value),0);r.innerText='Tu resultado: '+${JSON.stringify(results)}[s%${results.length}]">Ver resultado</button><div id="r" class="result"></div>`)}
switch(id){
case"porcentaje":page(names[id],f("Porcentaje (%)","p")+f("Número","n")+`<button class="btn" onclick="r.innerText=(+n.value*+p.value/100).toFixed(2)">Calcular</button><div id="r" class="result"></div>`);break;
case"iva":page(names[id],f("Precio (€)","n")+f("IVA (%)","p")+`<button class="btn" onclick="r.innerText='Con IVA: '+(+n.value*(1+ +p.value/100)).toFixed(2)+' € | Sin IVA: '+(+n.value/(1+ +p.value/100)).toFixed(2)+' €'">Calcular</button><div id="r" class="result"></div>`);break;
case"descuento":page(names[id],f("Precio original (€)","n")+f("Descuento (%)","p")+`<button class="btn" onclick="r.innerText=(+n.value*(1- +p.value/100)).toFixed(2)+' €'">Precio final</button><div id="r" class="result"></div>`);break;
case"edad":page(names[id],f("Fecha de nacimiento","d","date")+`<button class="btn" onclick="let x=new Date(d.value),now=new Date();let a=now.getFullYear()-x.getFullYear();if(new Date(now.getFullYear(),x.getMonth(),x.getDate())>now)a--;r.innerText=a+' años'">Calcular edad</button><div id="r" class="result"></div>`);break;
case"regla":page(names[id],f("A","a")+f("B","b")+f("C","c")+`<button class="btn" onclick="r.innerText=(+b.value*+c.value/+a.value).toFixed(2)">Calcular D</button><div id="r" class="result"></div>`);break;
case"media":case"notas":page(names[id],`<div class="field"><label>Notas separadas por comas</label><input id="n" placeholder="7, 8.5, 6, 9"></div><button class="btn" onclick="let x=n.value.split(',').map(Number).filter(x=>!isNaN(x));r.innerText=x.length?(x.reduce((a,b)=>a+b,0)/x.length).toFixed(2):'Añade notas'">Calcular</button><div id="r" class="result"></div>`);break;
case"ponderada":page(names[id],`<div class="field"><label>Notas</label><input id="n" placeholder="8, 6, 9"></div><div class="field"><label>Pesos (%)</label><input id="p" placeholder="30, 30, 40"></div><button class="btn" onclick="let n=n.value.split(',').map(Number),p=document.getElementById('p').value.split(',').map(Number);r.innerText=(n.reduce((s,v,i)=>s+v*(p[i]||0),0)/p.reduce((s,v)=>s+v,0)).toFixed(2)">Calcular</button><div id="r" class="result"></div>`);break;
case"tiempo":page(names[id],f("Horas","h")+f("Minutos","m")+f("Horas a sumar","h2")+f("Minutos a sumar","m2")+`<button class="btn" onclick="let x=(+h.value*60+ +m.value)+(+h2.value*60+ +m2.value);r.innerText=Math.floor(x/60)+' h '+x%60+' min'">Calcular</button><div id="r" class="result"></div>`);break;
case"conversor":page(names[id],f("Valor","v")+`<div class="field"><label>Conversión</label><select id="c"><option value="km-m">km → m</option><option value="m-km">m → km</option><option value="kg-g">kg → g</option><option value="g-kg">g → kg</option><option value="c-f">°C → °F</option><option value="f-c">°F → °C</option></select></div><button class="btn" onclick="let x=+v.value;let z={ 'km-m':x*1000,'m-km':x/1000,'kg-g':x*1000,'g-kg':x/1000,'c-f':x*9/5+32,'f-c':(x-32)*5/9}[c.value];r.innerText=z.toFixed(2)">Convertir</button><div id="r" class="result"></div>`);break;
case"numero":page(names[id],f("Mínimo","a")+f("Máximo","b")+`<button class="btn" onclick="r.innerText=Math.floor(Math.random()*(+b.value-+a.value+1))+ +a.value">Generar</button><div id="r" class="result"></div>`);break;
case"nombres":page(names[id],`<button class="btn" onclick="let a=['Lucas','Hugo','Álex','Leo','Mateo','Daniel','Martina','Sofía','Lucía','Emma','Valeria','Nora'];r.innerText=a[Math.floor(Math.random()*a.length)]">Generar nombre</button><div id="r" class="result"></div>`);break;
case"password":page(names[id],f("Longitud","l")+`<button class="btn" onclick="let c='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*';let s='';for(let i=0;i<+l.value;i++)s+=c[Math.floor(Math.random()*c.length)];r.innerText=s">Generar</button><div id="r" class="result"></div>`);break;
case"ruleta":case"decision":page(names[id],`<div class="field"><label>Opciones (una por línea)</label><textarea id="x" rows="8" placeholder="Pizza\nHamburguesa\nTacos"></textarea></div><button class="btn" onclick="let a=x.value.split('\\n').map(s=>s.trim()).filter(Boolean);r.innerText=a[Math.floor(Math.random()*a.length)]||'Añade opciones'">Elegir</button><div id="r" class="result"></div>`);break;
case"equipos":page(names[id],`<div class="field"><label>Personas (una por línea)</label><textarea id="x" rows="10"></textarea></div>${f("Número de equipos","k")}<button class="btn" onclick="let a=x.value.split('\\n').filter(Boolean).sort(()=>Math.random()-.5),o=[];for(let i=0;i<+k.value;i++)o.push([]);a.forEach((v,i)=>o[i%o.length].push(v));r.innerHTML=o.map((v,i)=>'Equipo '+(i+1)+': '+v.join(', ')).join('<br>')">Generar equipos</button><div id="r" class="result"></div>`);break;
case"caracteres":page(names[id],`<textarea id="x" rows="10" style="width:100%" oninput="r.innerText=x.value.length+' caracteres · '+x.value.replace(/\\s/g,'').length+' sin espacios'"></textarea><div id="r" class="result">0 caracteres</div>`);break;
case"palabras":page(names[id],`<textarea id="x" rows="10" style="width:100%" oninput="r.innerText=x.value.trim()?x.value.trim().split(/\\s+/).length+' palabras · '+x.value.length+' caracteres':'0 palabras · 0 caracteres'"></textarea><div id="r" class="result">0 palabras · 0 caracteres</div>`);break;
case"sueldo":page(names[id],f("Sueldo anual (€)","a")+f("Pagas al año","p")+`<button class="btn" onclick="r.innerText=(+a.value/+p.value).toFixed(2)+' € por paga (estimación bruta)'">Calcular</button><div id="r" class="result"></div>`);break;
case"beneficio":page(names[id],f("Precio de compra (€)","c")+f("Precio de venta (€)","v")+`<button class="btn" onclick="r.innerText='Beneficio: '+(+v.value-+c.value).toFixed(2)+' €'">Calcular</button><div id="r" class="result"></div>`);break;
case"margen":page(names[id],f("Coste (€)","c")+f("Venta (€)","v")+`<button class="btn" onclick="let b=+v.value-+c.value;r.innerText=(b/+v.value*100).toFixed(2)+'% de margen'">Calcular</button><div id="r" class="result"></div>`);break;
case"interes":page(names[id],f("Capital inicial (€)","c")+f("Interés anual (%)","i")+f("Años","a")+`<button class="btn" onclick="r.innerText=(+c.value*(1+ +i.value/100)**+a.value).toFixed(2)+' €'">Calcular</button><div id="r" class="result"></div>`);break;
case"imc":page(names[id],f("Peso (kg)","p")+f("Altura (m)","h")+`<button class="btn" onclick="r.innerText=(+p.value/(+h.value**2)).toFixed(1)">Calcular IMC</button><div id="r" class="result"></div>`);break;
case"calorias":page(names[id],f("Edad","a")+f("Peso (kg)","p")+f("Altura (cm)","h")+`<div class="field"><label>Sexo</label><select id="s"><option value="5">Hombre</option><option value="-161">Mujer</option></select></div><button class="btn" onclick="r.innerText=Math.round(10*+p.value+6.25*+h.value-5*+a.value+ +s.value)+' kcal/día aprox.'">Calcular</button><div id="r" class="result"></div><small>Estimación orientativa, no consejo médico.</small>`);break;
case"ritmo":page(names[id],f("Distancia (km)","d")+f("Tiempo (minutos)","t")+`<button class="btn" onclick="r.innerText=(+t.value/+d.value).toFixed(2)+' min/km'">Calcular ritmo</button><div id="r" class="result"></div>`);break;
case"distancia":page(names[id],f("Velocidad (km/h)","v")+f("Tiempo (horas)","t")+`<button class="btn" onclick="r.innerText=(+v.value*+t.value).toFixed(2)+' km'">Calcular distancia</button><div id="r" class="result"></div>`);break;
case"pomodoro":page(names[id],`<p>25 minutos de estudio.</p><button class="btn" onclick="let s=1500;clearInterval(window.x);window.x=setInterval(()=>{s--;r.innerText=Math.floor(s/60)+':'+String(s%60).padStart(2,'0');if(s<=0)clearInterval(window.x)},1000)">Empezar</button><div id="r" class="result">25:00</div>`);break;
case"gaming-generador":page(names[id],`<p>Genera un reto para tu partida.</p><button class="btn" onclick="let a=['Usa solo un arma','Juega sin curarte','Cambia de estrategia','Elige un personaje al azar','Intenta ganar sin morir'];r.innerText=a[Math.floor(Math.random()*a.length)]">Generar reto</button><div id="r" class="result"></div>`);break;
case"gaming-ruleta":page(names[id],`<textarea id="x" rows="7" style="width:100%" placeholder="Personaje 1\\nPersonaje 2\\nPersonaje 3"></textarea><button class="btn" onclick="let a=x.value.split('\\n').filter(Boolean);r.innerText=a[Math.floor(Math.random()*a.length)]||'Añade opciones'">Girar</button><div id="r" class="result"></div>`);break;
case"gaming-test":test(names[id],[["¿Qué prefieres?","Competitivo","Historia","Cooperativo"],["¿Qué te gusta más?","Acción","Explorar","Construir"],["¿Qué buscas?","Victoria","Diversión","Creatividad"]],["Jugador competitivo","Jugador explorador","Jugador creativo"]);break;
case"stranger":test(names[id],[["¿Qué harías ante un problema?","Investigar","Luchar","Ayudar"],["Tu estilo","Valiente","Analítico","Divertido"],["En un grupo eres...","Líder","Cerebro","El gracioso"]],["Eleven","Dustin","Steve"]);break;
case"marvel":test(names[id],[["Tu cualidad","Valor","Ingenio","Disciplina"],["Tu estilo","Poder","Tecnología","Estrategia"],["En equipo","Líder","Inventor","Guardián"]],["Capitán América","Iron Man","Spider-Man"]);break;
case"dc":test(names[id],[["Tu cualidad","Justicia","Inteligencia","Valentía"],["Tu estilo","Héroe","Detective","Guerrero"],["Tu lugar","Ciudad","Noche","Acción"]],["Superman","Batman","Wonder Woman"]);break;
case"pokemon":test(names[id],[["Tu elemento","Fuego","Agua","Planta"],["Tu personalidad","Valiente","Tranquilo","Curioso"],["Tu estilo","Ataque","Defensa","Velocidad"]],["Charmander","Squirtle","Bulbasaur"]);break;
case"mas-tests":page(names[id],`<p>Próximamente añadiremos más tests.</p><a class="btn" href="index.html">Ver herramientas</a>`);break;
default:page("Herramienta no encontrada",`<p>Esta herramienta todavía no existe.</p><a class="btn" href="index.html">Volver</a>`);
}